### ISSUE TITLE
Build fails with "ValueError: No JSON object could be decoded"

### ISSUE THREAD

**Issue by REBELinBLUE** [MattTuttle/sublime-ti-build#32]
If I try to run the build on iOS simulator I get this in the console.

Specifically

Traceback (most recent call last):
  File "./json/scanner.py", line 30, in _scan_once
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 32, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephen/Library/Application Support/Sublime Text 3/Packages/Titanium Build/Titanium.py", line 196, in select_ios_target
    self.load_ios_sdk_info()
  File "/Users/stephen/Library/Application Support/Sublime Text 3/Packages/Titanium Build/Titanium.py", line 344, in load_ios_sdk_info
    info = json.loads(result.decode('utf-8'))
  File "./json/**init**.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded

If I run the command it appears to be running, titanium info --types ios --output json I get back a valid json structure

**Comment by rkueny** [comment]
I've exactly the same bug "ValueError: No JSON object could be decoded"

Any solution ? :/

**Comment by REBELinBLUE** [comment]
The symlink worked for me

**Comment by rkueny** [comment]
As much for me, the symlink worked for me too :+1:

**Comment by clemblanco** [comment]
I confirm, the symlink does the trick. Not sure exactly why tho...
